## This is development compose file
## Some service mount the volumes to the respected folders
## Service that are volumes mounted: nginx, api, frontend

version: "3.9"
services:
  # Consumer
  consumer:
    image: node:16-alpine3.16
    working_dir: /app
    entrypoint: ["npm", "run", "dev-con"]
    volumes:
      - ./consumer.js:/app/consumer.js
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules

  # Publisher
  publisher:
    image: node:16-alpine3.16
    working_dir: /app
    entrypoint: ["npm", "run", "dev-pub"]
    volumes:
      - ./publisher.js:/app/publisher.js
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules

  # Message Queue
  nsqlookupd:
    image: nsqio/nsq
    restart: always
    command: /nsqlookupd
    expose:
      - 4160
      - 4161

  nsqd:
    image: nsqio/nsq
    restart: always
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    expose:
      - 4151
      - 4150

  nsqadmin:
    image: nsqio/nsq
    restart: always
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171
    expose:
      - 4171
